import React from 'react';
import { motion } from 'motion/react';
import { Presentation, Sparkles, Wand2 } from 'lucide-react';

export const Header: React.FC = () => {
  return (
    <motion.header 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="relative text-center py-20 px-4 mt-8"
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: 0.5, ease: "easeOut" }}
        className="inline-flex items-center gap-2 px-4 py-2 glass-card !rounded-full mb-8 border-white/5"
      >
        <span className="relative flex h-2 w-2">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
          <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
        </span>
        <span className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">
          Powered by Next-Gen AI
        </span>
      </motion.div>

      <motion.div 
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.2 }}
        className="flex items-center justify-center gap-4 mb-6"
      >
        <div className="bg-gradient-to-br from-primary to-primary-dark p-4 rounded-3xl shadow-2xl shadow-primary/20 relative group">
          <Presentation className="w-10 h-10 text-white" />
          <div className="absolute -top-2 -right-2 bg-accent p-1.5 rounded-full shadow-lg">
            <Sparkles className="w-3.5 h-3.5 text-white" />
          </div>
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight text-white">
          AI <span className="text-primary italic">PPT</span> Generator
        </h1>
      </motion.div>

      <motion.p 
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.3 }}
        className="text-xl md:text-2xl text-slate-400 max-w-2xl mx-auto font-medium leading-relaxed"
      >
        Turn your ideas into <span className="text-white">stunning presentations</span> instantly. 
        Professional decks, generated by intelligence.
      </motion.p>

      {/* Decorative Blur Elements */}
      <div className="absolute -top-10 left-1/2 -translate-x-1/2 w-96 h-96 bg-primary/10 blur-[120px] rounded-full -z-10" />
    </motion.header>
  );
};
